name: CMake CI

on:
  push:
    paths:
      - 'frontend/unibert-desktop-client/**'
      - '.github/workflows/cmake-single-platform.yml'
  pull_request:
    paths:
      - 'frontend/unibert-desktop-client/**'
      - '.github/workflows/cmake-single-platform.yml'

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: '13'
          check-path: 'frontend/unibert-desktop-client/'

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libgtest-dev \
          libgmock-dev \
          cmake \
          ninja-build \
          build-essential \
          libcurlpp-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.1'
          host: 'linux'
          target: 'desktop'

      - name: Configure CMake
        working-directory: frontend/unibert-desktop-client
        run: cmake -DCMAKE_PREFIX_PATH=~/Qt/6.8.1/gcc_64/lib/cmake/ -S . -B build -G Ninja

      - name: Build
        working-directory: frontend/unibert-desktop-client/build
        run: cmake --build .

      - name: Test
        working-directory: frontend/unibert-desktop-client/build
        run: ctest --output-on-failure
